# permissions for end users to view epgconfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: epg-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: epgconf-viewer-role
rules:
- apiGroups:
  - epg.custom.aci
  resources:
  - epgconfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - epg.custom.aci
  resources:
  - epgconfs/status
  verbs:
  - get
